services:
  streamlit-ui:
    build: ./frontend
    container_name: streamlit-ui
    ports:
      - "8501:8501"
    networks:
      - app_network
    depends_on:
      - rag-backend
    restart: always   # Add this line to automatically restart the container

  rag-backend:
    build: ./backend/api
    container_name: rag-backend
    ports:
      - "8000:8000"
    networks:
      - app_network
    restart: always   # Add this line for automatic restart

networks:
  app_network:
    driver: bridge